### ISSUE TITLE
 Issues when importing data (Building)

### ISSUE THREAD

**Issue by gioagu** [3dcitydb/energy-ade-citydb#3] opened 2021-04-21 11:27 UTC
The is a continuation of the former ticket. Similar tests, but with one buildings that has 1 ground surface, 1 roof surface, 1 wall surface. Again, KIT Energy ADE data.

Here WeatherData objects are associated to the building (1), the wall surface (1) and the roof surface (2).
They are all modelled via property "weatherData" of class (Energy ADE) CityObject.

Issues:
1) WeatherData objects ARE imported in this case
2) Same issues as before with data stored also in table CITYOBJECT for WeatherData and TimeSeries objects.

Again, small test data sample is attached.

[202104211_weather_data_building_KIT_Energy_ADE.zip](https://github.com/3dcitydb/energy-ade-citydb/files/6350415/202104211_weather_data_building_KIT_Energy_ADE.zip)

**Comment by clausnagel** [comment] 2021-04-22 16:58
Well, issue 1 is not a bug but expected behaviour, right? And issue 2 is neither a bug as explained here: https://github.com/3dcitydb/energy-ade-citydb/issues/2.

**Comment by gioagu** [comment] 2021-04-22 17:11
Indeed, "issue" 1 is actually not an issue, sorry ;-)

Thanks for the super quick reply!

**Comment by clausnagel** [comment] 2021-04-30 14:39
fixed in version [1.2.1](https://github.com/3dcitydb/energy-ade-citydb/releases/tag/v1.2.1)

**Closed as completed by clausnagel** 2021-04-30 14:39 UTC
